#ifndef RAIL_OPERATIONS_SYSTEM_ENVIRONMENT_UICONSTANTS_H
#define RAIL_OPERATIONS_SYSTEM_ENVIRONMENT_UICONSTANTS_H

const float horizontalPadding = 10;
const float verticalPadding = 5;

#endif //RAIL_OPERATIONS_SYSTEM_ENVIRONMENT_UICONSTANTS_H